prefix hydra: <http://www.w3.org/ns/hydra/core#>
prefix dcterms: <http://purl.org/dc/terms/>
prefix sch: <http://schema.org/>

construct
{
  @container 
    a hydra:PagedCollection ;
    hydra:member ?issue ;
    hydra:totalItems ?count.

  ?source sch:issueNumber ?number
}
where
{
  optional {
    select ?issue ?number
    {
      ?issue sch:isPartOf @magazine ;
             sch:issueNumber ?number .  
    }
    order by ?number
    limit @limit
    offset @offset
  }

  {
    select count(*) as ?count
    {
      ?issue sch:isPartOf @magazine . 
    }
  }
}