prefix hydra: <http://www.w3.org/ns/hydra/core#>
prefix dcterms: <http://purl.org/dc/terms/>
prefix sch: <http://schema.org/>
prefix foaf: <http://xmlns.com/foaf/0.1/>

construct
{
  @container
    a hydra:PagedCollection ;
    hydra:member ?issue ;
    hydra:totalItems ?count.

  ?source sch:issueNumber ?number
}
where
{
  ?graph foaf:primaryTopic @collection .

  optional {
    select ?source ?number
    {
      GRAPH ?graph 
      { 
        @collection hydra:member ?issue .
        ?issue sch:issueNumber ?number .  
      }
    }
    order by ?number
    limit @limit
    offset @offset
  }

  {
    select count(*) as ?count    
    {
     GRAPH ?graph { @collection hydra:member ?i . }
    }
  }
}