prefix hydra: <http://www.w3.org/ns/hydra/core#>
prefix dcterms: <http://purl.org/dc/terms/>

construct
{
  @container 
    a hydra:PagedCollection ;
    hydra:member ?source ;
    hydra:totalItems ?count.

  ?source dcterms:title ?title
}
where
{

  optional {
    select ?source ?title
    {
    graph ?g {
      ?source a @type .  
      ?source dcterms:title ?title
      }
    }
    order by ?title
    limit @limit
    offset @offset
  }

  {
    select count(*) as ?count
    {
      graph ?g { ?source a @type . }
    }
  }
}