install:
  - choco install gitversion.portable -pre -y
  
before_build:
  - .paket\paket.bootstrapper.exe prerelease
  - .paket\paket.exe restore
  - ps: gitversion /l console /output buildserver

services:
  - mssql2014

build:
  publish_wap: true  

configuration:  
  - Debug
  - Release 
  
deploy:
  - provider: Environment
    name: '[TEST] data.wikibus.org'
    on:
      Configuration: Debug
      branch: master
  - provider: Environment
    name: '[TEST] wikibus.org'
    on:
      Configuration: Debug
      branch: master
