before_build:
  - restore_packages.bat
services:
  - mssql2008r2sp2

build:
  publish_wap: true  

configuration: Release  

deploy:
  - provider: WebDeploy
    server: https://46.163.66.159:8172/msdeploy.axd?site=data.test.wikibus.org
    website: data.test.wikibus.org
    username: wikibus
    password: 
      secure: ckU8LWLgCV94A6K92I9scA==
    ntlm: false
    remove_files: true
    artifact: data.wikibus.org.zip
    skip_files: paket.references; FodyWeavers.xml
