before_build:
  - restore_packages.bat
services:
  - mssql2008r2sp2

build:
  publish_wap: true  

configuration:  
  - Staging
  - Release 

deploy:
  - provider: Environment
    name: wikibus.org API test
    on:
      Configuration: Staging
  - provider: Environment
    name: wikibus.org PURL test
    on:
      Configuration: Staging
