before_build:
  - restore_packages.bat

build:
  publish_wap: true  

configuration: Release  

deploy:
  - provider: WebDeploy
    server: http://t-code.com.pl
    website: api.test.wikibus.org
    username: deploy
    password: 
      secure: ckU8LWLgCV94A6K92I9scA==
    ntlm: false
    remove_files: true
    app_offline: false
    artifact: wikibus.web.zip
    on:
      branch: master
      platform: x86
      configuration: Release