before_build:
  - restore_packages.bat

build:
  publish_wap: true  

configuration: Release  

deploy:
  - provider: WebDeploy
    server: https://46.163.66.159:8172/msdeploy.axd?site=api.test.wikibus.org
    website: api.test.wikibus.org
    username: wikibus
    password: 
      secure: ckU8LWLgCV94A6K92I9scA==
    ntlm: false
    remove_files: true
    artifact: wikibus.web.zip
    skip_files: paket.references; FodyWeavers.xml