before_build:
  - restore_packages.bat

deploy:
  - provider: WebDeploy
    server: http://t-code.com.pl
    website: api.test.wikibus.org
    username: deploy
    password: 
      secure: ckU8LWLgCV94A6K92I9scA==
    ntlm: false
    remove_files: false
    app_offline: false
    on:
      branch: master
      platform: x86
      configuration: release
  - provider: Environment
    name: staging
	on:
	  branch: master