// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace wikibus.tests.Modules
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Getting Sources")]
    public partial class GettingSourcesFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "GettingSources.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Getting Sources", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("GETting sources")]
        [NUnit.Framework.TestCaseAttribute("brochure", "/brochure/12345", null)]
        [NUnit.Framework.TestCaseAttribute("book", "/book/123456abc", null)]
        [NUnit.Framework.TestCaseAttribute("magazine", "/magazine/Bus%20Kurier", null)]
        public virtual void GETtingSources(string type, string path, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GETting sources", exampleTags);
#line 3
this.ScenarioSetup(scenarioInfo);
#line 4
   testRunner.Given("Accept header is \'text/turtle\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 5
   testRunner.And(string.Format("existing {0} \'http://wikibus.org{1}\'", type, path), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 6
   testRunner.When(string.Format("I GET resource \'{0}\'", path), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 7
   testRunner.Then("response should have status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 8
   testRunner.And(string.Format("{0} \'http://wikibus.org{1}\' should have been retrieved", type, path), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("GET inexistent brochure")]
        public virtual void GETInexistentBrochure()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GET inexistent brochure", ((string[])(null)));
#line 15
this.ScenarioSetup(scenarioInfo);
#line 16
   testRunner.Given("brochure \'http://wikibus.org/brochure/12345\' doesn\'t exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 17
   testRunner.When("I GET resource \'/brochure/12345\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 18
   testRunner.Then("response should have status 404", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("GET collection first page")]
        [NUnit.Framework.TestCaseAttribute("book", "/books", null)]
        [NUnit.Framework.TestCaseAttribute("brochure", "/brochures", null)]
        [NUnit.Framework.TestCaseAttribute("magazine", "/magazines", null)]
        public virtual void GETCollectionFirstPage(string type, string path, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GET collection first page", exampleTags);
#line 20
this.ScenarioSetup(scenarioInfo);
#line 21
   testRunner.Given("Accept header is \'text/turtle\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 22
     testRunner.And(string.Format("exisiting {0} collection", type), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
    testRunner.When(string.Format("I GET resource \'{0}\'", path), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 24
    testRunner.Then("response should have status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 25
     testRunner.And(string.Format("page 1 of {0} collection should have been retrieved", type), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("GET collection negative page")]
        [NUnit.Framework.TestCaseAttribute("book", "/books", null)]
        [NUnit.Framework.TestCaseAttribute("brochure", "/brochures", null)]
        [NUnit.Framework.TestCaseAttribute("magazine", "/magazines", null)]
        public virtual void GETCollectionNegativePage(string type, string path, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GET collection negative page", exampleTags);
#line 32
this.ScenarioSetup(scenarioInfo);
#line 33
   testRunner.Given("Accept header is \'text/turtle\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "key",
                        "value"});
            table1.AddRow(new string[] {
                        "page",
                        "-1"});
#line 34
  testRunner.And("query string is", ((string)(null)), table1, "And ");
#line 37
    testRunner.When(string.Format("I GET resource \'{0}\'", path), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 38
    testRunner.Then("response should have status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("GET source collection Nth page")]
        [NUnit.Framework.TestCaseAttribute("book", "/books", null)]
        [NUnit.Framework.TestCaseAttribute("brochure", "/brochures", null)]
        [NUnit.Framework.TestCaseAttribute("magazine", "/magazines", null)]
        public virtual void GETSourceCollectionNthPage(string type, string path, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GET source collection Nth page", exampleTags);
#line 45
this.ScenarioSetup(scenarioInfo);
#line 46
   testRunner.Given("Accept header is \'text/turtle\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 47
     testRunner.And(string.Format("exisiting {0} collection", type), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "key",
                        "value"});
            table2.AddRow(new string[] {
                        "page",
                        "25"});
#line 48
  testRunner.And("query string is", ((string)(null)), table2, "And ");
#line 51
    testRunner.When(string.Format("I GET resource \'{0}\'", path), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 52
    testRunner.Then("response should have status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 53
     testRunner.And(string.Format("page 25 of {0} collection should have been retrieved", type), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("GET images")]
        [NUnit.Framework.TestCaseAttribute("/book/10/image", "10", null)]
        [NUnit.Framework.TestCaseAttribute("/brochure/15/image", "15", null)]
        [NUnit.Framework.TestCaseAttribute("/book/10/image/small", "10", null)]
        [NUnit.Framework.TestCaseAttribute("/brochure/15/image/small", "15", null)]
        public virtual void GETImages(string url, string id, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GET images", exampleTags);
#line 60
this.ScenarioSetup(scenarioInfo);
#line 61
   testRunner.Given("Accept header is \'*/*\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 62
     testRunner.And(string.Format("exisiting image {0}", id), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 63
    testRunner.When(string.Format("I GET resource \'{0}\'", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 64
    testRunner.Then("response should have status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 65
     testRunner.And("content type should be \'image/jpeg\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 66
     testRunner.And(string.Format("image {0} should have been retrieved", id), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("GET issue image")]
        [NUnit.Framework.TestCaseAttribute("/magazine/Buses/issue/66/image", null)]
        [NUnit.Framework.TestCaseAttribute("/magazine/Buses/issue/66/image/small", null)]
        public virtual void GETIssueImage(string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GET issue image", exampleTags);
#line 74
this.ScenarioSetup(scenarioInfo);
#line 75
   testRunner.Given("Accept header is \'*/*\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 76
     testRunner.And("exisiting image for Buses 66", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 77
    testRunner.When(string.Format("I GET resource \'{0}\'", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 78
    testRunner.Then("response should have status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 79
     testRunner.And("content type should be \'image/jpeg\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 80
     testRunner.And("image Buses 66 should have been retrieved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("GET missing image")]
        [NUnit.Framework.TestCaseAttribute("/book/10/image/large", null)]
        [NUnit.Framework.TestCaseAttribute("/brochure/15/image/large", null)]
        [NUnit.Framework.TestCaseAttribute("/magazine/Buses/issue/66/image/large", null)]
        [NUnit.Framework.TestCaseAttribute("/book/10/image/small", null)]
        [NUnit.Framework.TestCaseAttribute("/brochure/15/image/small", null)]
        [NUnit.Framework.TestCaseAttribute("/magazine/Buses/issue/66/image/small", null)]
        public virtual void GETMissingImage(string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("GET missing image", exampleTags);
#line 86
this.ScenarioSetup(scenarioInfo);
#line 87
   testRunner.Given("Accept header is \'*/*\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 88
    testRunner.When(string.Format("I GET resource \'{0}\'", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 89
    testRunner.Then("response should have status 404", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
