// <auto-generated />
using System;

namespace wikibus.common.Vocabularies
{
    /// <summary>The Bibliographic Ontology (http://purl.org/ontology/bibo/).</summary>
    public static partial class Bibo
    {
#pragma warning disable 1591 // ReSharper disable InconsistentNaming
        public const string Prefix="bibo";

        public const string BaseUri="http://purl.org/ontology/bibo/";
#pragma warning restore 1591 // ReSharper restore InconsistentNaming
    }
}