









// <auto-generated />
using System;

namespace wikibus.common.Vocabularies
{
    /// <summary>The Bibliographic Ontology (http://purl.org/ontology/bibo/).</summary>
    public static partial class Bibo
    {
        /// <summary>
        /// bibo
        /// </summary>
        public const string Prefix="bibo";

        /// <summary>
        /// http://purl.org/ontology/bibo/
        /// </summary>
        public const string BaseUri="http://purl.org/ontology/bibo/";

        
        /// <summary>
        /// A scholarly academic article, typically published in a journal.
        /// </summary>
        public const string AcademicArticle = BaseUri + "AcademicArticle";

        
        /// <summary>
        /// A written composition in prose, usually nonfiction, on a specific topic, forming an independent part of a book or other publication, as a newspaper or magazine.
        /// </summary>
        public const string Article = BaseUri + "Article";

        
        /// <summary>
        /// An audio document; aka record.
        /// </summary>
        public const string AudioDocument = BaseUri + "AudioDocument";

        
        /// <summary>
        /// An audio-visual document; film, video, and so forth.
        /// </summary>
        public const string AudioVisualDocument = BaseUri + "AudioVisualDocument";

        
        /// <summary>
        /// Draft legislation presented for discussion to a legal body.
        /// </summary>
        public const string Bill = BaseUri + "Bill";

        
        /// <summary>
        /// A written or printed work of fiction or nonfiction, usually on sheets of paper fastened or bound together within covers.
        /// </summary>
        public const string Book = BaseUri + "Book";

        
        /// <summary>
        /// A section of a book.
        /// </summary>
        public const string BookSection = BaseUri + "BookSection";

        
        /// <summary>
        /// A written argument submitted to a court.
        /// </summary>
        public const string Brief = BaseUri + "Brief";

        
        /// <summary>
        /// A chapter of a book.
        /// </summary>
        public const string Chapter = BaseUri + "Chapter";

        
        /// <summary>
        /// A collection of statutes.
        /// </summary>
        public const string Code = BaseUri + "Code";

        
        /// <summary>
        /// A document that simultaneously contains other documents.
        /// </summary>
        public const string CollectedDocument = BaseUri + "CollectedDocument";

        
        /// <summary>
        /// A collection of Documents or Collections
        /// </summary>
        public const string Collection = BaseUri + "Collection";

        
        /// <summary>
        /// A meeting for consultation or discussion.
        /// </summary>
        public const string Conference = BaseUri + "Conference";

        
        /// <summary>
        /// A collection of legal cases.
        /// </summary>
        public const string CourtReporter = BaseUri + "CourtReporter";

        
        /// <summary>
        /// A document (noun) is a bounded physical representation of body of information designed with the capacity (and usually intent) to communicate. A document may manifest symbolic, diagrammatic or sensory-representational information.
        /// </summary>
        public const string Document = BaseUri + "Document";

        
        /// <summary>
        /// a distinct part of a larger document or collected document.
        /// </summary>
        public const string DocumentPart = BaseUri + "DocumentPart";

        
        /// <summary>
        /// The status of the publication of a document.
        /// </summary>
        public const string DocumentStatus = BaseUri + "DocumentStatus";

        
        /// <summary>
        /// An edited book.
        /// </summary>
        public const string EditedBook = BaseUri + "EditedBook";

        
        /// <summary>
        /// A written communication addressed to a person or organization and transmitted electronically.
        /// </summary>
        public const string Email = BaseUri + "Email";

        
        /// <summary>
        /// Event
        /// </summary>
        public const string Event = BaseUri + "Event";

        
        /// <summary>
        /// A passage selected from a larger work.
        /// </summary>
        public const string Excerpt = BaseUri + "Excerpt";

        
        /// <summary>
        /// aka movie.
        /// </summary>
        public const string Film = BaseUri + "Film";

        
        /// <summary>
        /// An instance or a session in which testimony and arguments are presented, esp. before an official, as a judge in a lawsuit.
        /// </summary>
        public const string Hearing = BaseUri + "Hearing";

        
        /// <summary>
        /// A document that presents visual or diagrammatic information.
        /// </summary>
        public const string Image = BaseUri + "Image";

        
        /// <summary>
        /// A formalized discussion between two or more people.
        /// </summary>
        public const string Interview = BaseUri + "Interview";

        
        /// <summary>
        /// something that is printed or published and distributed, esp. a given number of a periodical
        /// </summary>
        public const string Issue = BaseUri + "Issue";

        
        /// <summary>
        /// A periodical of scholarly journal Articles.
        /// </summary>
        public const string Journal = BaseUri + "Journal";

        
        /// <summary>
        /// A document accompanying a legal case.
        /// </summary>
        public const string LegalCaseDocument = BaseUri + "LegalCaseDocument";

        
        /// <summary>
        /// A document containing an authoritative determination (as a decree or judgment) made after consideration of facts or law.
        /// </summary>
        public const string LegalDecision = BaseUri + "LegalDecision";

        
        /// <summary>
        /// A legal document; for example, a court decision, a brief, and so forth.
        /// </summary>
        public const string LegalDocument = BaseUri + "LegalDocument";

        
        /// <summary>
        /// A legal document proposing or enacting a law or a group of laws.
        /// </summary>
        public const string Legislation = BaseUri + "Legislation";

        
        /// <summary>
        /// A written or printed communication addressed to a person or organization and usually transmitted by mail.
        /// </summary>
        public const string Letter = BaseUri + "Letter";

        
        /// <summary>
        /// A periodical of magazine Articles. A magazine is a publication that is issued periodically, usually bound in a paper cover, and typically contains essays, stories, poems, etc., by many writers, and often photographs and drawings, frequently specializing in a particular subject or area, as hobbies, news, or sports.
        /// </summary>
        public const string Magazine = BaseUri + "Magazine";

        
        /// <summary>
        /// A small reference book, especially one giving instructions.
        /// </summary>
        public const string Manual = BaseUri + "Manual";

        
        /// <summary>
        /// An unpublished Document, which may also be submitted to a publisher for publication.
        /// </summary>
        public const string Manuscript = BaseUri + "Manuscript";

        
        /// <summary>
        /// A graphical depiction of geographic features.
        /// </summary>
        public const string Map = BaseUri + "Map";

        
        /// <summary>
        /// A loose, thematic, collection of Documents, often Books.
        /// </summary>
        public const string MultiVolumeBook = BaseUri + "MultiVolumeBook";

        
        /// <summary>
        /// A periodical of documents, usually issued daily or weekly, containing current news, editorials, feature articles, and usually advertising.
        /// </summary>
        public const string Newspaper = BaseUri + "Newspaper";

        
        /// <summary>
        /// Notes or annotations about a resource.
        /// </summary>
        public const string Note = BaseUri + "Note";

        
        /// <summary>
        /// A document describing the exclusive right granted by a government to an inventor to manufacture, use, or sell an invention for a certain number of years.
        /// </summary>
        public const string Patent = BaseUri + "Patent";

        
        /// <summary>
        /// A public performance.
        /// </summary>
        public const string Performance = BaseUri + "Performance";

        
        /// <summary>
        /// A group of related documents issued at regular intervals.
        /// </summary>
        public const string Periodical = BaseUri + "Periodical";

        
        /// <summary>
        /// A communication between an agent and one or more specific recipients.
        /// </summary>
        public const string PersonalCommunication = BaseUri + "PersonalCommunication";

        
        /// <summary>
        /// A personal communication manifested in some document.
        /// </summary>
        public const string PersonalCommunicationDocument = BaseUri + "PersonalCommunicationDocument";

        
        /// <summary>
        /// A compilation of documents published from an event, such as a conference.
        /// </summary>
        public const string Proceedings = BaseUri + "Proceedings";

        
        /// <summary>
        /// An excerpted collection of words.
        /// </summary>
        public const string Quote = BaseUri + "Quote";

        
        /// <summary>
        /// A document that presents authoritative reference information, such as a dictionary or encylopedia .
        /// </summary>
        public const string ReferenceSource = BaseUri + "ReferenceSource";

        
        /// <summary>
        /// A document describing an account or statement describing in detail an event, situation, or the like, usually as the result of observation, inquiry, etc..
        /// </summary>
        public const string Report = BaseUri + "Report";

        
        /// <summary>
        /// A loose, thematic, collection of Documents, often Books.
        /// </summary>
        public const string Series = BaseUri + "Series";

        
        /// <summary>
        /// A slide in a slideshow
        /// </summary>
        public const string Slide = BaseUri + "Slide";

        
        /// <summary>
        /// A presentation of a series of slides, usually presented in front of an audience with written text and images.
        /// </summary>
        public const string Slideshow = BaseUri + "Slideshow";

        
        /// <summary>
        /// A document describing a standard
        /// </summary>
        public const string Standard = BaseUri + "Standard";

        
        /// <summary>
        /// A bill enacted into law.
        /// </summary>
        public const string Statute = BaseUri + "Statute";

        
        /// <summary>
        /// A document created to summarize research findings associated with the completion of an academic degree.
        /// </summary>
        public const string Thesis = BaseUri + "Thesis";

        
        /// <summary>
        /// The academic degree of a Thesis
        /// </summary>
        public const string ThesisDegree = BaseUri + "ThesisDegree";

        
        /// <summary>
        /// A web page is an online document available (at least initially) on the world wide web. A web page is written first and foremost to appear on the web, as distinct from other online resources such as books, manuscripts or audio documents which use the web primarily as a distribution mechanism alongside other more traditional methods such as print.
        /// </summary>
        public const string Webpage = BaseUri + "Webpage";

        
        /// <summary>
        /// A group of Webpages accessible on the Web.
        /// </summary>
        public const string Website = BaseUri + "Website";

        
        /// <summary>
        /// A seminar, discussion group, or the like, that emphasizes zxchange of ideas and the demonstration and application of techniques, skills, etc.
        /// </summary>
        public const string Workshop = BaseUri + "Workshop";

        
        /// <summary>
        /// A summary of the resource.
        /// </summary>
        public const string @abstract = BaseUri + "abstract";

        
        /// <summary>
        /// The date on which a legal case is argued before a court. Date is of format xsd:date
        /// </summary>
        public const string argued = BaseUri + "argued";

        
        /// <summary>
        /// asin
        /// </summary>
        public const string asin = BaseUri + "asin";

        
        /// <summary>
        /// An chapter number
        /// </summary>
        public const string chapter = BaseUri + "chapter";

        
        /// <summary>
        /// coden
        /// </summary>
        public const string coden = BaseUri + "coden";

        
        /// <summary>
        /// This property is for a plain-text rendering of the content of a Document. While the plain-text content of an entire document could be described by this property.
        /// </summary>
        public const string content = BaseUri + "content";

        
        /// <summary>
        /// doi
        /// </summary>
        public const string doi = BaseUri + "doi";

        
        /// <summary>
        /// eanucc13
        /// </summary>
        public const string eanucc13 = BaseUri + "eanucc13";

        
        /// <summary>
        /// The name defining a special edition of a document. Normally its a literal value composed of a version number and words.
        /// </summary>
        public const string edition = BaseUri + "edition";

        
        /// <summary>
        /// eissn
        /// </summary>
        public const string eissn = BaseUri + "eissn";

        
        /// <summary>
        /// gtin14
        /// </summary>
        public const string gtin14 = BaseUri + "gtin14";

        
        /// <summary>
        /// handle
        /// </summary>
        public const string handle = BaseUri + "handle";

        
        /// <summary>
        /// identifier
        /// </summary>
        public const string identifier = BaseUri + "identifier";

        
        /// <summary>
        /// isbn
        /// </summary>
        public const string isbn = BaseUri + "isbn";

        
        /// <summary>
        /// isbn10
        /// </summary>
        public const string isbn10 = BaseUri + "isbn10";

        
        /// <summary>
        /// isbn13
        /// </summary>
        public const string isbn13 = BaseUri + "isbn13";

        
        /// <summary>
        /// issn
        /// </summary>
        public const string issn = BaseUri + "issn";

        
        /// <summary>
        /// An issue number
        /// </summary>
        public const string issue = BaseUri + "issue";

        
        /// <summary>
        /// lccn
        /// </summary>
        public const string lccn = BaseUri + "lccn";

        
        /// <summary>
        /// A description (often numeric) that locates an item within a containing document or collection.
        /// </summary>
        public const string locator = BaseUri + "locator";

        
        /// <summary>
        /// The number of pages contained in a document
        /// </summary>
        public const string numPages = BaseUri + "numPages";

        
        /// <summary>
        /// The number of volumes contained in a collection of documents (usually a series, periodical, etc.).
        /// </summary>
        public const string numVolumes = BaseUri + "numVolumes";

        
        /// <summary>
        /// A generic item or document number. Not to be confused with issue number.
        /// </summary>
        public const string number = BaseUri + "number";

        
        /// <summary>
        /// oclcnum
        /// </summary>
        public const string oclcnum = BaseUri + "oclcnum";

        
        /// <summary>
        /// Ending page number within a continuous page range.
        /// </summary>
        public const string pageEnd = BaseUri + "pageEnd";

        
        /// <summary>
        /// Starting page number within a continuous page range.
        /// </summary>
        public const string pageStart = BaseUri + "pageStart";

        
        /// <summary>
        /// A string of non-contiguous page spans that locate a Document within a Collection. Example: 23-25, 34, 54-56. For continuous page ranges, use the pageStart and pageEnd properties.
        /// </summary>
        public const string pages = BaseUri + "pages";

        
        /// <summary>
        /// pmid
        /// </summary>
        public const string pmid = BaseUri + "pmid";

        
        /// <summary>
        /// The prefix of a name
        /// </summary>
        public const string prefixName = BaseUri + "prefixName";

        
        /// <summary>
        /// A section number
        /// </summary>
        public const string section = BaseUri + "section";

        
        /// <summary>
        /// shortDescription
        /// </summary>
        public const string shortDescription = BaseUri + "shortDescription";

        
        /// <summary>
        /// The abbreviation of a title.
        /// </summary>
        public const string shortTitle = BaseUri + "shortTitle";

        
        /// <summary>
        /// sici
        /// </summary>
        public const string sici = BaseUri + "sici";

        
        /// <summary>
        /// The suffix of a name
        /// </summary>
        public const string suffixName = BaseUri + "suffixName";

        
        /// <summary>
        /// upc
        /// </summary>
        public const string upc = BaseUri + "upc";

        
        /// <summary>
        /// Universal Resource Identifier of a document
        /// </summary>
        public const string uri = BaseUri + "uri";

        
        /// <summary>
        /// A volume number
        /// </summary>
        public const string volume = BaseUri + "volume";

        
        /// <summary>
        /// A legal decision that affirms a ruling.
        /// </summary>
        public const string affirmedBy = BaseUri + "affirmedBy";

        
        /// <summary>
        /// Critical or explanatory note for a Document.
        /// </summary>
        public const string annotates = BaseUri + "annotates";

        
        /// <summary>
        /// An ordered list of authors. Normally, this list is seen as a priority list that order authors by importance.
        /// </summary>
        public const string authorList = BaseUri + "authorList";

        
        /// <summary>
        /// Relates a document to another document that cites the first document.
        /// </summary>
        public const string citedBy = BaseUri + "citedBy";

        
        /// <summary>
        /// Relates a document to another document that is cited by the first document as reference, comment, review, quotation or for another purpose.
        /// </summary>
        public const string cites = BaseUri + "cites";

        
        /// <summary>
        /// An ordered list of contributors. Normally, this list is seen as a priority list that order contributors by importance.
        /// </summary>
        public const string contributorList = BaseUri + "contributorList";

        
        /// <summary>
        /// A court associated with a legal document; for example, that which issues a decision.
        /// </summary>
        public const string court = BaseUri + "court";

        
        /// <summary>
        /// The thesis degree.
        /// </summary>
        public const string degree = BaseUri + "degree";

        
        /// <summary>
        /// A Film director.
        /// </summary>
        public const string director = BaseUri + "director";

        
        /// <summary>
        /// Distributor of a document or a collection of documents.
        /// </summary>
        public const string distributor = BaseUri + "distributor";

        
        /// <summary>
        /// A person having managerial and sometimes policy-making responsibility for the editorial part of a publishing firm or of a newspaper, magazine, or other publication.
        /// </summary>
        public const string editor = BaseUri + "editor";

        
        /// <summary>
        /// An ordered list of editors. Normally, this list is seen as a priority list that order editors by importance.
        /// </summary>
        public const string editorList = BaseUri + "editorList";

        
        /// <summary>
        /// An agent that is interviewed by another agent.
        /// </summary>
        public const string interviewee = BaseUri + "interviewee";

        
        /// <summary>
        /// An agent that interview another agent.
        /// </summary>
        public const string interviewer = BaseUri + "interviewer";

        
        /// <summary>
        /// An entity responsible for issuing often informally published documents such as press releases, reports, etc.
        /// </summary>
        public const string issuer = BaseUri + "issuer";

        
        /// <summary>
        /// The organizer of an event; includes conference organizers, but also government agencies or other bodies that are responsible for conducting hearings.
        /// </summary>
        public const string organizer = BaseUri + "organizer";

        
        /// <summary>
        /// Owner of a document or a collection of documents.
        /// </summary>
        public const string owner = BaseUri + "owner";

        
        /// <summary>
        /// performer
        /// </summary>
        public const string performer = BaseUri + "performer";

        
        /// <summary>
        /// Relates a document to an event; for example, a paper to a conference.
        /// </summary>
        public const string presentedAt = BaseUri + "presentedAt";

        
        /// <summary>
        /// Relates an event to associated documents; for example, conference to a paper.
        /// </summary>
        public const string presents = BaseUri + "presents";

        
        /// <summary>
        /// Producer of a document or a collection of documents.
        /// </summary>
        public const string producer = BaseUri + "producer";

        
        /// <summary>
        /// An agent that receives a communication document.
        /// </summary>
        public const string recipient = BaseUri + "recipient";

        
        /// <summary>
        /// The resource in which another resource is reproduced.
        /// </summary>
        public const string reproducedIn = BaseUri + "reproducedIn";

        
        /// <summary>
        /// A legal decision that reverses a ruling.
        /// </summary>
        public const string reversedBy = BaseUri + "reversedBy";

        
        /// <summary>
        /// Relates a review document to a reviewed thing (resource, item, etc.).
        /// </summary>
        public const string reviewOf = BaseUri + "reviewOf";

        
        /// <summary>
        /// The publication status of (typically academic) content.
        /// </summary>
        public const string status = BaseUri + "status";

        
        /// <summary>
        /// A legal decision on appeal that takes action on a case (affirming it, reversing it, etc.).
        /// </summary>
        public const string subsequentLegalDecision = BaseUri + "subsequentLegalDecision";

        
        /// <summary>
        /// Relates a document to some transcribed original.
        /// </summary>
        public const string transcriptOf = BaseUri + "transcriptOf";

        
        /// <summary>
        /// Relates a translated document to the original document.
        /// </summary>
        public const string translationOf = BaseUri + "translationOf";

        
        /// <summary>
        /// A person who translates written document from one language to another.
        /// </summary>
        public const string translator = BaseUri + "translator";

    }
}