// <auto-generated />
namespace wikibus.common.Vocabularies
{
    /// <summary>
    /// Additional schema.org properties
    /// </summary>
    public static partial class Schema
    {
        /// <summary>
        /// The name property
        /// </summary>
        public const string name = BaseUri + "name";
    }
}
