// <auto-generated />
using System;

namespace wikibus.common.Vocabularies
{
    /// <summary>Dublin Core Metadata Element Set, Version 1.1 (http://purl.org/dc/elements/1.1/).</summary>
    public static partial class Dc
    {
        public const string Prefix="dc";

        public const string BaseUri="http://purl.org/dc/elements/1.1/";
        
        /// <summary>
        /// An entity responsible for making contributions to the resource.
        /// </summary>
        public const string contributor = BaseUri + "contributor";
        
        /// <summary>
        /// The spatial or temporal topic of the resource, the spatial applicability of the resource, or the jurisdiction under which the resource is relevant.
        /// </summary>
        public const string coverage = BaseUri + "coverage";
        
        /// <summary>
        /// An entity primarily responsible for making the resource.
        /// </summary>
        public const string creator = BaseUri + "creator";
        
        /// <summary>
        /// A point or period of time associated with an event in the lifecycle of the resource.
        /// </summary>
        public const string date = BaseUri + "date";
        
        /// <summary>
        /// An account of the resource.
        /// </summary>
        public const string description = BaseUri + "description";
        
        /// <summary>
        /// The file format, physical medium, or dimensions of the resource.
        /// </summary>
        public const string format = BaseUri + "format";
        
        /// <summary>
        /// An unambiguous reference to the resource within a given context.
        /// </summary>
        public const string identifier = BaseUri + "identifier";
        
        /// <summary>
        /// A language of the resource.
        /// </summary>
        public const string language = BaseUri + "language";
        
        /// <summary>
        /// An entity responsible for making the resource available.
        /// </summary>
        public const string publisher = BaseUri + "publisher";
        
        /// <summary>
        /// A related resource.
        /// </summary>
        public const string relation = BaseUri + "relation";
        
        /// <summary>
        /// Information about rights held in and over the resource.
        /// </summary>
        public const string rights = BaseUri + "rights";
        
        /// <summary>
        /// A related resource from which the described resource is derived.
        /// </summary>
        public const string source = BaseUri + "source";
        
        /// <summary>
        /// The topic of the resource.
        /// </summary>
        public const string subject = BaseUri + "subject";
        
        /// <summary>
        /// A name given to the resource.
        /// </summary>
        public const string title = BaseUri + "title";
        
        /// <summary>
        /// The nature or genre of the resource.
        /// </summary>
        public const string type = BaseUri + "type";
    }
}