// <auto-generated />
using System;

namespace wikibus.common.Vocabularies
{
    /// <summary>The Hydra Core Vocabulary (http://www.w3.org/ns/hydra/core#).</summary>
    public static partial class Hydra
    {
#pragma warning disable 1591 // ReSharper disable InconsistentNaming
        public const string Prefix="hydra";

        public const string BaseUri="http://www.w3.org/ns/hydra/core#";

        public static readonly Uri Class=new Uri(BaseUri+"Class");

        public static readonly Uri statusCode=new Uri(BaseUri+"statusCode");

        public static readonly Uri writeonly=new Uri(BaseUri+"writeonly");

        public static readonly Uri mapping=new Uri(BaseUri+"mapping");

        public static readonly Uri description=new Uri(BaseUri+"description");

        public static readonly Uri itemsPerPage=new Uri(BaseUri+"itemsPerPage");

        public static readonly Uri freetextQuery=new Uri(BaseUri+"freetextQuery");

        public static readonly Uri property=new Uri(BaseUri+"property");

        public static readonly Uri @readonly=new Uri(BaseUri+"readonly");

        public static readonly Uri method=new Uri(BaseUri+"method");

        public static readonly Uri template=new Uri(BaseUri+"template");

        public static readonly Uri required=new Uri(BaseUri+"required");

        public static readonly Uri title=new Uri(BaseUri+"title");

        public static readonly Uri variable=new Uri(BaseUri+"variable");

        public static readonly Uri totalItems=new Uri(BaseUri+"totalItems");

        public static readonly Uri ApiDocumentation=new Uri(BaseUri+"ApiDocumentation");

        public static readonly Uri Collection=new Uri(BaseUri+"Collection");

        public static readonly Uri PagedCollection=new Uri(BaseUri+"PagedCollection");

        public static readonly Uri TemplatedLink=new Uri(BaseUri+"TemplatedLink");

        public static readonly Uri IriTemplate=new Uri(BaseUri+"IriTemplate");

        public static readonly Uri Resource=new Uri(BaseUri+"Resource");

        public static readonly Uri Operation=new Uri(BaseUri+"Operation");

        public static readonly Uri Link=new Uri(BaseUri+"Link");

        public static readonly Uri StatusCodeDescription=new Uri(BaseUri+"StatusCodeDescription");

        public static readonly Uri SupportedProperty=new Uri(BaseUri+"SupportedProperty");

        public static readonly Uri Error=new Uri(BaseUri+"Error");

        public static readonly Uri DeleteResourceOperation=new Uri(BaseUri+"DeleteResourceOperation");

        public static readonly Uri CreateResourceOperation=new Uri(BaseUri+"CreateResourceOperation");

        public static readonly Uri IriTemplateMapping=new Uri(BaseUri+"IriTemplateMapping");

        public static readonly Uri ReplaceResourceOperation=new Uri(BaseUri+"ReplaceResourceOperation");
#pragma warning restore 1591 // ReSharper restore InconsistentNaming
    }
}