// <auto-generated />
namespace wikibus.common.Vocabularies
{
    /// <summary>
    /// Lexvo language vocabulary
    /// </summary>
    public static class Lexvo
    {
        /// <summary>
        /// The base URI
        /// </summary>
        public const string BaseUri = "http://lexvo.org/";

        /// <summary>
        /// Namespace for ISO 336-1 language codes
        /// </summary>
        public const string iso639_1 = BaseUri + "id/iso639-1/";
    }
}
