// <auto-generated />
using System;

namespace wikibus.common.Vocabularies
{
    /// <summary>SwetoDblp Ontology (http://lsdis.cs.uga.edu/projects/semdis/opus#).</summary>
    public static partial class Opus
    {
        public const string Prefix="opus";

        public const string BaseUri="http://lsdis.cs.uga.edu/projects/semdis/opus#";
        
        /// <summary>
        /// An article from a journal or magazine.
        /// </summary>
        public const string Article = BaseUri + "Article";
        
        /// <summary>
        /// An article in the proceedings of a meeting, such as a conference, workhshop and symposium.
        /// </summary>
        public const string Article_in_Proceedings = BaseUri + "Article_in_Proceedings";
        
        /// <summary>
        /// A book with an explicit publisher.
        /// </summary>
        public const string Book = BaseUri + "Book";
        
        /// <summary>
        /// A part of a book, such as a chapter (or section/preface) and/or a range of pages.
        /// </summary>
        public const string Book_Chapter = BaseUri + "Book_Chapter";
        
        /// <summary>
        /// A dissertation written to receive a PhD.
        /// </summary>
        public const string Doctoral_Dissertation = BaseUri + "Doctoral_Dissertation";
        
        /// <summary>
        /// An edited book with an explicit publisher.
        /// </summary>
        public const string Edited_Book = BaseUri + "Edited_Book";
        
        /// <summary>
        /// An edited publication, that is, it has one or more editors (edited books, etc)
        /// </summary>
        public const string Edited_Publication = BaseUri + "Edited_Publication";
        
        /// <summary>
        /// A periodical presenting articles on a particular subject.
        /// </summary>
        public const string Journal = BaseUri + "Journal";
        
        /// <summary>
        /// A thesis written to receive a Master's degree.
        /// </summary>
        public const string Masters_Thesis = BaseUri + "Masters_Thesis";
        
        /// <summary>
        /// A written account of what transpired at a meeting.
        /// </summary>
        public const string Proceedings = BaseUri + "Proceedings";
        
        /// <summary>
        /// Individual documents and collections of documents such as series, journals, etc.
        /// </summary>
        public const string Publication = BaseUri + "Publication";
        
        /// <summary>
        /// An organization that, among other things, creates publishing periodicals, books or music.
        /// </summary>
        public const string Publishing_Organization = BaseUri + "Publishing_Organization";
        
        /// <summary>
        /// An organization where individuals receive education.
        /// </summary>
        public const string School = BaseUri + "School";
        
        /// <summary>
        /// A periodical that appears at scheduled times.
        /// </summary>
        public const string Serial_Publication = BaseUri + "Serial_Publication";
        
        /// <summary>
        /// Publication Series, such as LNCS, WEUR Workshops, etc. (at this time debatable whether this should be subclassof Publication)
        /// </summary>
        public const string Series = BaseUri + "Series";
        
        /// <summary>
        /// A treatise advancing a new point of view resulting from research; usually a requirement for an advanced academic degree.
        /// </summary>
        public const string Thesis = BaseUri + "Thesis";
        
        /// <summary>
        /// An institution for higher learning with teaching and research facilities constituting a graduate school and professional schools that award master's degrees and doctorates and an undergraduate division that awards bachelor's degrees.
        /// </summary>
        public const string University = BaseUri + "University";
        
        /// <summary>
        /// A webpage, it is subclass of Document because we want to emphasize that the URL of the webpage is used the URI.
        /// </summary>
        public const string Webpage = BaseUri + "Webpage";
        
        /// <summary>
        /// An alternative Book Title or the Book Title where an article appears, such as title of proceedings.
        /// </summary>
        public const string book_title = BaseUri + "book_title";
        
        /// <summary>
        /// The CDROM location of a Publication, as used by the ACM SIGMOD Anthology.
        /// </summary>
        public const string cdrom = BaseUri + "cdrom";
        
        /// <summary>
        /// The chapter number of a publication
        /// </summary>
        public const string chapter = BaseUri + "chapter";
        
        /// <summary>
        /// The Electronic Edition of a publication
        /// </summary>
        public const string ee = BaseUri + "ee";
        
        /// <summary>
        /// The Electronic Edition of a Presentation of a publication
        /// </summary>
        public const string eepresentation = BaseUri + "eepresentation";
        
        /// <summary>
        /// The ISBN of a publication.
        /// </summary>
        public const string isbn = BaseUri + "isbn";
        
        /// <summary>
        /// The name of a Journal, such as where an article appears
        /// </summary>
        public const string journal_name = BaseUri + "journal_name";
        
        /// <summary>
        /// The last modified date of a document.
        /// </summary>
        public const string last_modified_date = BaseUri + "last_modified_date";
        
        /// <summary>
        /// The month part of the date of a foaf:Document.
        /// </summary>
        public const string month = BaseUri + "month";
        
        /// <summary>
        /// The month part of the date of a foaf:Document represented as xsd:gMonth value
        /// </summary>
        public const string gMonth = BaseUri + "gMonth";
        
        /// <summary>
        /// The Number part of citation of a publication.
        /// </summary>
        public const string number = BaseUri + "number";
        
        /// <summary>
        /// The Pages part of citation of a publication.
        /// </summary>
        public const string pages = BaseUri + "pages";
        
        /// <summary>
        /// The Volume part of citation of a publication.
        /// </summary>
        public const string volume = BaseUri + "volume";
        
        /// <summary>
        /// The year part of the date of a foaf:Document.
        /// </summary>
        public const string year = BaseUri + "year";
        
        /// <summary>
        /// The abstract of a document
        /// </summary>
        public const string @abstract = BaseUri + "abstract";
        
        /// <summary>
        /// Indicates that a publication originates or is related to a specific Organization.
        /// </summary>
        public const string at_organization = BaseUri + "at_organization";
        
        /// <summary>
        /// Indicates that a publication originates or is related to a specific University.
        /// </summary>
        public const string at_university = BaseUri + "at_university";
        
        /// <summary>
        /// Indicates that a book chapter belongs to a specific book. It is debateable whether this should be subclass of Collection.
        /// </summary>
        public const string chapter_of = BaseUri + "chapter_of";
        
        /// <summary>
        /// Indicates that a publication cites another publication.
        /// </summary>
        public const string cites = BaseUri + "cites";
        
        /// <summary>
        /// Indicates that a publication is included in a specific proceedings publication.
        /// </summary>
        public const string isIncludedIn = BaseUri + "isIncludedIn";
        
        /// <summary>
        /// Indicates that a publication has a specific editor(s).
        /// </summary>
        public const string editor = BaseUri + "editor";
        
        /// <summary>
        /// Indicates that a person is affiliated to a specific organization.
        /// </summary>
        public const string affiliation = BaseUri + "affiliation";
        
        /// <summary>
        /// Indicates that a Publication is part of a Publication Series.
        /// </summary>
        public const string in_series = BaseUri + "in_series";
        
        /// <summary>
        /// Indicates that a publication is authored by a specific person(s).
        /// </summary>
        public const string author = BaseUri + "author";
        
        /// <summary>
        /// Indicates that a person is co-editor with another person
        /// </summary>
        public const string coeditor = BaseUri + "coeditor";
        
        /// <summary>
        /// Indicates that a person is co-author with another person
        /// </summary>
        public const string coauthor = BaseUri + "coauthor";
        
        /// <summary>
        /// Indicates that a person has same affiliation than another person (this is not necessarily transitive)
        /// </summary>
        public const string sameAffiliation = BaseUri + "sameAffiliation";
    }
}