// <auto-generated />
using System;

namespace wikibus.common.Vocabularies
{
    /// <summary>SwetoDblp Ontology (http://lsdis.cs.uga.edu/projects/semdis/opus#).</summary>
    public static partial class Opus
    {
#pragma warning disable 1591 // ReSharper disable InconsistentNaming
        public const string Prefix="opus";

        public const string BaseUri="http://lsdis.cs.uga.edu/projects/semdis/opus#";

        public static readonly Uri Article=new Uri(BaseUri+"Article");

        public static readonly Uri Article_in_Proceedings=new Uri(BaseUri+"Article_in_Proceedings");

        public static readonly Uri Book=new Uri(BaseUri+"Book");

        public static readonly Uri Book_Chapter=new Uri(BaseUri+"Book_Chapter");

        public static readonly Uri Doctoral_Dissertation=new Uri(BaseUri+"Doctoral_Dissertation");

        public static readonly Uri Edited_Book=new Uri(BaseUri+"Edited_Book");

        public static readonly Uri Edited_Publication=new Uri(BaseUri+"Edited_Publication");

        public static readonly Uri Journal=new Uri(BaseUri+"Journal");

        public static readonly Uri Masters_Thesis=new Uri(BaseUri+"Masters_Thesis");

        public static readonly Uri Proceedings=new Uri(BaseUri+"Proceedings");

        public static readonly Uri Publication=new Uri(BaseUri+"Publication");

        public static readonly Uri Publishing_Organization=new Uri(BaseUri+"Publishing_Organization");

        public static readonly Uri School=new Uri(BaseUri+"School");

        public static readonly Uri Serial_Publication=new Uri(BaseUri+"Serial_Publication");

        public static readonly Uri Series=new Uri(BaseUri+"Series");

        public static readonly Uri Thesis=new Uri(BaseUri+"Thesis");

        public static readonly Uri University=new Uri(BaseUri+"University");

        public static readonly Uri Webpage=new Uri(BaseUri+"Webpage");

        public static readonly Uri book_title=new Uri(BaseUri+"book_title");

        public static readonly Uri cdrom=new Uri(BaseUri+"cdrom");

        public static readonly Uri chapter=new Uri(BaseUri+"chapter");

        public static readonly Uri ee=new Uri(BaseUri+"ee");

        public static readonly Uri eepresentation=new Uri(BaseUri+"eepresentation");

        public static readonly Uri isbn=new Uri(BaseUri+"isbn");

        public static readonly Uri journal_name=new Uri(BaseUri+"journal_name");

        public static readonly Uri last_modified_date=new Uri(BaseUri+"last_modified_date");

        public static readonly Uri month=new Uri(BaseUri+"month");

        public static readonly Uri gMonth=new Uri(BaseUri+"gMonth");

        public static readonly Uri number=new Uri(BaseUri+"number");

        public static readonly Uri pages=new Uri(BaseUri+"pages");

        public static readonly Uri volume=new Uri(BaseUri+"volume");

        public static readonly Uri year=new Uri(BaseUri+"year");

        public static readonly Uri @abstract=new Uri(BaseUri+"abstract");

        public static readonly Uri at_organization=new Uri(BaseUri+"at_organization");

        public static readonly Uri at_university=new Uri(BaseUri+"at_university");

        public static readonly Uri chapter_of=new Uri(BaseUri+"chapter_of");

        public static readonly Uri cites=new Uri(BaseUri+"cites");

        public static readonly Uri isIncludedIn=new Uri(BaseUri+"isIncludedIn");

        public static readonly Uri editor=new Uri(BaseUri+"editor");

        public static readonly Uri affiliation=new Uri(BaseUri+"affiliation");

        public static readonly Uri in_series=new Uri(BaseUri+"in_series");

        public static readonly Uri author=new Uri(BaseUri+"author");

        public static readonly Uri coeditor=new Uri(BaseUri+"coeditor");

        public static readonly Uri coauthor=new Uri(BaseUri+"coauthor");

        public static readonly Uri sameAffiliation=new Uri(BaseUri+"sameAffiliation");
#pragma warning restore 1591 // ReSharper restore InconsistentNaming
    }
}