// <auto-generated />
using System;

namespace wikibus.common.Vocabularies
{
    /// <summary>The RDF Vocabulary (RDF) (http://www.w3.org/1999/02/22-rdf-syntax-ns#).</summary>
    public static partial class Rdf
    {
        public const string Prefix="rdf";

        public const string BaseUri="http://www.w3.org/1999/02/22-rdf-syntax-ns#";
        
        /// <summary>
        /// The class of RDF properties.
        /// </summary>
        public const string Property = BaseUri + "Property";
        
        /// <summary>
        /// The class of RDF statements.
        /// </summary>
        public const string Statement = BaseUri + "Statement";
        
        /// <summary>
        /// The class of unordered containers.
        /// </summary>
        public const string Bag = BaseUri + "Bag";
        
        /// <summary>
        /// The class of ordered containers.
        /// </summary>
        public const string Seq = BaseUri + "Seq";
        
        /// <summary>
        /// The class of containers of alternatives.
        /// </summary>
        public const string Alt = BaseUri + "Alt";
        
        /// <summary>
        /// The class of RDF Lists.
        /// </summary>
        public const string List = BaseUri + "List";
        
        /// <summary>
        /// The subject is an instance of a class.
        /// </summary>
        public const string type = BaseUri + "type";
        
        /// <summary>
        /// The subject of the subject RDF statement.
        /// </summary>
        public const string subject = BaseUri + "subject";
        
        /// <summary>
        /// The predicate of the subject RDF statement.
        /// </summary>
        public const string predicate = BaseUri + "predicate";
        
        /// <summary>
        /// The object of the subject RDF statement.
        /// </summary>
        public const string @object = BaseUri + "object";
        
        /// <summary>
        /// Idiomatic property used for structured values.
        /// </summary>
        public const string value = BaseUri + "value";
        
        /// <summary>
        /// The first item in the subject RDF list.
        /// </summary>
        public const string first = BaseUri + "first";
        
        /// <summary>
        /// The rest of the subject RDF list after the first item.
        /// </summary>
        public const string rest = BaseUri + "rest";
        /// <summary>
        /// The empty list, with no items in it. If the rest of a list is nil then the list has no more items in it.
        /// </summary>
        public const string nil = BaseUri + "nil";
    }
}