// <auto-generated />
using System;

namespace wikibus.common.Vocabularies
{
    /// <summary>The RDF Schema vocabulary (RDFS) (http://www.w3.org/2000/01/rdf-schema#).</summary>
    public static partial class Rdfs
    {
        public const string Prefix="rdfs";

        public const string BaseUri="http://www.w3.org/2000/01/rdf-schema#";
        
        /// <summary>
        /// The class resource, everything.
        /// </summary>
        public const string Resource = BaseUri + "Resource";
        
        /// <summary>
        /// The class of classes.
        /// </summary>
        public const string Class = BaseUri + "Class";
        
        /// <summary>
        /// The class of literal values, eg. textual strings and integers.
        /// </summary>
        public const string Literal = BaseUri + "Literal";
        
        /// <summary>
        /// The class of RDF containers.
        /// </summary>
        public const string Container = BaseUri + "Container";
        
        /// <summary>
        /// The class of container membership properties, rdf:_1, rdf:_2, ..., all of which are sub-properties of 'member'.
        /// </summary>
        public const string ContainerMembershipProperty = BaseUri + "ContainerMembershipProperty";
        
        /// <summary>
        /// The class of RDF datatypes.
        /// </summary>
        public const string Datatype = BaseUri + "Datatype";
        
        /// <summary>
        /// The subject is a subclass of a class.
        /// </summary>
        public const string subClassOf = BaseUri + "subClassOf";
        
        /// <summary>
        /// The subject is a subproperty of a property.
        /// </summary>
        public const string subPropertyOf = BaseUri + "subPropertyOf";
        
        /// <summary>
        /// A description of the subject resource.
        /// </summary>
        public const string comment = BaseUri + "comment";
        
        /// <summary>
        /// A human-readable name for the subject.
        /// </summary>
        public const string label = BaseUri + "label";
        
        /// <summary>
        /// A domain of the subject property.
        /// </summary>
        public const string domain = BaseUri + "domain";
        
        /// <summary>
        /// A range of the subject property.
        /// </summary>
        public const string range = BaseUri + "range";
        
        /// <summary>
        /// Further information about the subject resource.
        /// </summary>
        public const string seeAlso = BaseUri + "seeAlso";
        
        /// <summary>
        /// The defininition of the subject resource.
        /// </summary>
        public const string isDefinedBy = BaseUri + "isDefinedBy";
        
        /// <summary>
        /// A member of the subject resource.
        /// </summary>
        public const string member = BaseUri + "member";
    }
}