









// <auto-generated />
using System;

namespace wikibus.common.Vocabularies
{
    /// <summary>Wikibus.org Ontology (http://wikibus.org/ontology#).</summary>
    public static partial class Wbo
    {
        public const string Prefix="wbo";

        public const string BaseUri="http://wikibus.org/ontology#";

        
        /// <summary>
        /// A boook about public transport.
        /// </summary>
        public static readonly Uri Book=new Uri(BaseUri+"Book");

    }
}