// <auto-generated />
namespace wikibus.common.Vocabularies
{
    /// <summary>XML Schema Vocabulary (http://www.w3.org/2001/XMLSchema#).</summary>
    public static partial class Xsd
    {
        public const string Prefix = "xsd";

        public const string BaseUri = "http://www.w3.org/2001/XMLSchema#";
    }
}