// <auto-generated />
namespace wikibus.common.Vocabularies
{
    /// <summary>XML Schema Vocabulary (http://www.w3.org/2001/XMLSchema#).</summary>
    public static partial class Xsd
    {
        public const string Prefix = "xsd";

        public const string BaseUri = "http://www.w3.org/2001/XMLSchema#";

        public const string gYear = BaseUri + "gYear";

        public const string gMonth = BaseUri + "gMonth";

        public const string date = BaseUri + "date";

        public const string @string = BaseUri + "string";

        public const string integer = BaseUri + "integer";

        public const string boolean = BaseUri + "boolean";
    }
}