// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace wikibus.tests.Mappings
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Mapping Brochures from SQL to RDF")]
    public partial class MappingBrochuresFromSQLToRDFFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "MappingBrochures.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Mapping Brochures from SQL to RDF", " Make sure that correct RDF is returned for SQL rows", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Mapping brochure row")]
        public virtual void MappingBrochureRow()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Mapping brochure row", ((string[])(null)));
#line 4
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "SourceType",
                        "Language",
                        "Language2",
                        "Pages",
                        "FolderName"});
            table1.AddRow(new string[] {
                        "1",
                        "folder",
                        "tr",
                        "en",
                        "2",
                        "Türkkar City Angel E.D."});
#line 5
   testRunner.Given("table Sources.Source with data:", ((string)(null)), table1, "Given ");
#line 8
   testRunner.When("retrieve all triples", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
   testRunner.Then("resulting dataset should contain \'5\' triples", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 10
   testRunner.And("resulting dataset should match query:", @"base <http://wikibus.org/>
prefix wbo: <http://wikibus.org/ontology#>
prefix bibo: <http://purl.org/ontology/bibo/>
prefix dcterms: <http://purl.org/dc/terms/>

ASK
{
   <brochure/1> 
      a wbo:Brochure ;
      bibo:pages 2 ;
      dcterms:title ""Türkkar City Angel E.D."" ;
      dcterms:language <http://www.lexvo.org/page/iso639-1/tr>, 
                       <http://www.lexvo.org/page/iso639-1/en> .
}", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Mapping brochure and book with image")]
        public virtual void MappingBrochureAndBookWithImage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Mapping brochure and book with image", ((string[])(null)));
#line 28
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "SourceType",
                        "Image"});
            table2.AddRow(new string[] {
                        "1",
                        "folder",
                        "3qAAAA=="});
            table2.AddRow(new string[] {
                        "407",
                        "book",
                        "3qAAAA=="});
#line 29
   testRunner.Given("table Sources.Source with data:", ((string)(null)), table2, "Given ");
#line 33
   testRunner.When("retrieve all triples", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 34
   testRunner.Then("resulting dataset should contain \'8\' triples", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 35
   testRunner.And("resulting dataset should match query:", @"base <http://wikibus.org/>
prefix sch: <http://schema.org/>

ASK
{
   <brochure/1> 
      sch:image [
          a sch:ImageObject ;
          sch:contentUrl ""http://wikibus.org/brochure/1/image""^^sch:URL
      ].
      
   <book/407> 
      sch:image [
          a sch:ImageObject ;
          sch:contentUrl ""http://wikibus.org/book/407/image""^^sch:URL
      ].
}", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Mapping brochure row with date")]
        public virtual void MappingBrochureRowWithDate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Mapping brochure row with date", ((string[])(null)));
#line 56
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "SourceType",
                        "Language",
                        "Language2",
                        "Pages",
                        "Year",
                        "Month",
                        "Day",
                        "FolderCode",
                        "FolderName"});
            table3.AddRow(new string[] {
                        "6",
                        "folder",
                        "pl",
                        "NULL",
                        "2",
                        "2006",
                        "9",
                        "21",
                        "BED 81419 2006-09-21 POL Version 2",
                        "Fakty: Autobus turystyczny Volvo B9r/Sunsundegui Elegance"});
#line 57
   testRunner.Given("table Sources.Source with data:", ((string)(null)), table3, "Given ");
#line 60
   testRunner.When("retrieve all triples", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 61
   testRunner.Then("resulting dataset should contain \'8\' triples", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 62
   testRunner.And("resulting dataset should match query:", @"base <http://wikibus.org/>
prefix wbo: <http://wikibus.org/ontology#>
prefix bibo: <http://purl.org/ontology/bibo/>
prefix dcterms: <http://purl.org/dc/terms/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix opus: <http://lsdis.cs.uga.edu/projects/semdis/opus#>
prefix langIso: <http://www.lexvo.org/page/iso639-1/>

ASK
{
   <brochure/6> 
      a wbo:Brochure ;
      bibo:pages 2 ;
      dcterms:title ""Fakty: Autobus turystyczny Volvo B9r/Sunsundegui Elegance"" ;
      opus:year ""2006""^^xsd:gYear ;
      opus:month ""9""^^xsd:gMonth ;
      dcterms:date ""2006-9-21""^^xsd:date ;
      dcterms:language langIso:pl ;
      dcterms:identifier ""BED 81419 2006-09-21 POL Version 2"" .
}", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Mapping brochure row with incomplete date")]
        public virtual void MappingBrochureRowWithIncompleteDate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Mapping brochure row with incomplete date", ((string[])(null)));
#line 86
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "SourceType",
                        "Language",
                        "Language2",
                        "Pages",
                        "Year",
                        "FolderCode",
                        "FolderName"});
            table4.AddRow(new string[] {
                        "6",
                        "folder",
                        "pl",
                        "NULL",
                        "2",
                        "2006",
                        "BED 81419 2006-09-21 POL Version 2",
                        "Fakty: Autobus turystyczny Volvo B9r/Sunsundegui Elegance"});
#line 87
   testRunner.Given("table Sources.Source with data:", ((string)(null)), table4, "Given ");
#line 90
   testRunner.When("retrieve all triples", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 91
   testRunner.Then("resulting dataset should contain \'6\' triples", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 92
   testRunner.And("resulting dataset should not match query:", "base <http://wikibus.org/>\r\nprefix dcterms: <http://purl.org/dc/terms/>\r\n\r\nASK\r\n{" +
                    "\r\n   <brochure/6> dcterms:date ?date\r\n}", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Mapping complete book row")]
        public virtual void MappingCompleteBookRow()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Mapping complete book row", ((string[])(null)));
#line 103
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "SourceType",
                        "Language",
                        "Language2",
                        "Pages",
                        "Year",
                        "BookTitle",
                        "BookAuthor",
                        "BookISBN"});
            table5.AddRow(new string[] {
                        "407",
                        "book",
                        "pl",
                        "NULL",
                        "140",
                        "2010",
                        "Pojazdy samochodowe i przyczepy Jelcz 1952-1970",
                        "Wojciech Polomski",
                        "9788320617412"});
#line 104
   testRunner.Given("table Sources.Source with data:", ((string)(null)), table5, "Given ");
#line 107
    testRunner.When("retrieve all triples", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 108
    testRunner.Then("resulting dataset should contain \'8\' triples", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 109
     testRunner.And("resulting dataset should match query:", @" base <http://wikibus.org/>
 prefix wbo: <http://wikibus.org/ontology#>
 prefix bibo: <http://purl.org/ontology/bibo/>
 prefix dcterms: <http://purl.org/dc/terms/>
 prefix xsd: <http://www.w3.org/2001/XMLSchema#>
 prefix opus: <http://lsdis.cs.uga.edu/projects/semdis/opus#>
 prefix langIso: <http://www.lexvo.org/page/iso639-1/>
 prefix sch: <http://schema.org/>

 ASK
 {
    <book/407> a wbo:Book ;
       dcterms:title ""Pojazdy samochodowe i przyczepy Jelcz 1952-1970"" ;
       sch:isbn ""9788320617412"" ;
       sch:author [ sch:name ""Wojciech Polomski"" ] ;
       bibo:pages 140 ;
       opus:year ""2010""^^xsd:gYear ;
       dcterms:language langIso:pl .
 }", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Mapping complete magazine issue")]
        public virtual void MappingCompleteMagazineIssue()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Mapping complete magazine issue", ((string[])(null)));
#line 132
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "SourceType",
                        "Language",
                        "Pages",
                        "Year",
                        "Month",
                        "MagIssueMagazine",
                        "MagIssueNumber",
                        "Image"});
            table6.AddRow(new string[] {
                        "324",
                        "magissue",
                        "pl",
                        "16",
                        "2007",
                        "3",
                        "1",
                        "13",
                        "3qAAAA=="});
#line 133
   testRunner.Given("table Sources.Source with data:", ((string)(null)), table6, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name"});
            table7.AddRow(new string[] {
                        "1",
                        "Bus Kurier"});
#line 136
     testRunner.And("table Sources.Magazine with data:", ((string)(null)), table7, "And ");
#line 139
    testRunner.When("retrieve all triples", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 140
    testRunner.Then("resulting dataset should contain \'13\' triples", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 141
     testRunner.And("resulting dataset should match query:", @" base <http://wikibus.org/>
 prefix wbo: <http://wikibus.org/ontology#>
 prefix bibo: <http://purl.org/ontology/bibo/>
 prefix dcterms: <http://purl.org/dc/terms/>
 prefix xsd: <http://www.w3.org/2001/XMLSchema#>
 prefix opus: <http://lsdis.cs.uga.edu/projects/semdis/opus#>
 prefix langIso: <http://www.lexvo.org/page/iso639-1/>
 prefix sch: <http://schema.org/>

 ASK
 {
    <magazine/Bus%20Kurier/issue/13> a sch:PublicationIssue ;
       sch:image [
           a sch:ImageObject ;
           sch:contentUrl ""http://wikibus.org/magazine/Bus Kurier/issue/13/image""^^sch:URL 
       ] ;
       sch:issueNumber ""13""^^xsd:string ;
       sch:isPartOf <magazine/Bus%20Kurier> ;
       bibo:pages 16 ;
       opus:year ""2007""^^xsd:gYear ;
       opus:month ""3""^^xsd:gMonth ;
       dcterms:language langIso:pl .
 }", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
